name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      
  build-ubuntu-glut:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make GLUT_OR_GLFW=_USE_GLUT_
      
  build-ubuntu-no-graphics:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make GUIFLAG=
